"""UI 默认配置。"""

from nzfz_executor.ui.config.defaults import (
    DEFAULT_EXECUTOR_LOG_TIME_FORMAT,
    DEFAULT_EXECUTOR_PROGRESS_LOG_ENABLED,
    DEFAULT_EXECUTOR_STOP_TIMEOUT_MS,
    DEFAULT_MAX_EXECUTOR_LOG_LINES,
    DEFAULT_SCREENSHOT_TIMEOUT_MS,
)

__all__ = [
    "DEFAULT_EXECUTOR_LOG_TIME_FORMAT",
    "DEFAULT_EXECUTOR_PROGRESS_LOG_ENABLED",
    "DEFAULT_EXECUTOR_STOP_TIMEOUT_MS",
    "DEFAULT_MAX_EXECUTOR_LOG_LINES",
    "DEFAULT_SCREENSHOT_TIMEOUT_MS",
]
