"""UI 层默认配置常量（P2-06）。"""

from __future__ import annotations

DEFAULT_MAX_EXECUTOR_LOG_LINES = 1000

DEFAULT_SCREENSHOT_TIMEOUT_MS = 5_000
DEFAULT_EXECUTOR_STOP_TIMEOUT_MS = 10_000

DEFAULT_EXECUTOR_LOG_TIME_FORMAT = "%H:%M:%S"
DEFAULT_EXECUTOR_PROGRESS_LOG_ENABLED = True

DEFAULT_ACTION_DRY_RUN = True
DEFAULT_EXECUTOR_MAX_ITERATIONS = 1
DEFAULT_EXECUTOR_LOOP_INTERVAL_MS = 500

DEFAULT_RECOGNIZER_TYPE = "template"
DEFAULT_TEMPLATE_DIR = "resources/templates"
DEFAULT_TEMPLATE_MATCH_THRESHOLD = 0.85
DEFAULT_TEMPLATE_MATCH_GRAYSCALE = True
DEFAULT_TEMPLATE_EXTENSIONS = (".png", ".jpg", ".jpeg", ".bmp")
